name: Multi-Platform CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmake-generator: Ninja
          - os: macos-latest
            cmake-generator: Unix Makefiles
          - os: windows-latest
            cmake-generator: "NMake Makefiles"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@v4

      - name: Install dependencies
        run: |
          if ${{ matrix.os == 'ubuntu-latest' }}; then
            sudo apt-get update && sudo apt-get install -y ninja-build
          elif ${{ matrix.os == 'macos-latest' }}; then
            brew install ninja
          elif ${{ matrix.os == 'windows-latest' }}; then
            choco install ninja
          fi

      - name: Configure Meson with CMake
        run: cmake -S . -B build -G ${{ matrix.cmake-generator }}

      - name: Build with Meson
        run: cd build && meson setup --buildtype release . && ninja

      - name: Run tests
        run: cd build && ./lc0 --test
