name: Meson Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build libblas-dev libopenblas-dev
          # Install CUDA
          sudo apt-get install -y nvidia-cuda-toolkit
          # Install ONNX
          # sudo apt-get install -y libonnxruntime-dev

      - name: Configure Meson
        run: meson setup --backend ninja --buildtype release builddir -Dblas=true -Dcudnn=true

      - name: Build with Meson
        run: ninja -C builddir

      - name: Run tests
        run: ./builddir/lc0 --test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: lc0-ubuntu-latest
          path: builddir
