name: Multi-Platform Meson Build with CUDA, ONNX, and BLAS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, debian-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Update submodules
        run: |
         git submodule sync --recursive
         git submodule update --init --recursive
        
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y meson 
          sudo apt-get install -y ninja-build 
          sudo apt-get install -y libblas-dev 
          sudo apt-get install -y libopenblas-dev
          # Install CUDA
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
            choco install meson --installargs 'ADD_MESON_TO_PATH=System' -y
            #choco install ninja --installargs 'ADD_NINJA_TO_PATH=System' -y
            

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          curl -sSL http://developer.download.nvidia.com/compute/cuda/10.2/Prod/network_installers/cuda_10.2.89_win10_network.exe -o cuda_installer.exe
          ./cuda_installer.exe -s

      - name: Set Meson Path
        if: runner.os == 'Windows'
        run: |
          echo "$env:Path += ';C:\Program Files\Meson\meson.exe'" >> $Env:GITHUB_ENV
        shell: pwsh

      - name: Configure Meson(Windows)
        if: runner.os == 'Windows'
        run: |
            meson setup --buildtype release build -Dblas=true -Dcuda=true

      - name: Configure Meson(Linux)      
        if: runner.os == 'Linux'
        run: |
            meson setup --buildtype release builddir -Dblas=true -Dcuda=true

      - name: Build with Meson(Windows)
        if: runner.os == 'Windows'
        run: |
            ninja -C builddir
      - name: Build with Meson(Linux)
        if: runner.os == 'Linux'
        run: |
            ninja -C builddir

      - name: Run tests
        run: ./builddir/lc0 --benchmark

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: lc0-${{ matrix.os }}
          path: builddir
